### PR TITLE
Add consoleUserAgentDeviceType option.

### PR DESCRIPTION
**Pull request by Minaru**
Add custom option for console, so those who wants another result in type when a console is detected can (instead of 'tv').

### CODE REVIEW

**Comment by rguerreiro** [comment]
Not sure if the naming is the right one, though. It could be misleading. You could have a smart TV that isn't a console. Should we separate them both? I mean, one for console and another specific for TVs?

**Comment by Minaru** [comment]
I separated them both already, i returned the consoleUserAgentDeviceType only in the `if` case where we detect a Xbox/PS3-4/Wii or Wii U. Smart tvs still return hardcoded 'tv' type. The fact i left the console default value to 'tv' is for backward compatibility. Those who used to consider a console as a tv won't have a new case to handle, while those wanting to have special results for a console can by passing it through the option object.

Of course i can do the same and create a tvUserAgentDeviceType option, with 'tv' as default, allowing you to change the returned type for tvs. To be honest it would be great if we could custom each kind of device. Hardcoded strings for returns aren't that great, considering you can already customize some return types, but not all of them. I can take care of it if you want :)

What could be great also is detecting portable consoles. At the moment, I think DS/PSP or other kind of special console browser are detected by the last `else` case which gives them a unknownUserAgentDeviceType. If we could detect them, we can add them to a new `if` case, returning a consoleUserAgentDeviceType.

Should i also add a commit which update the README for the new option(s)?

**Comment by rguerreiro** [comment]
Please also add the tvUserAgentDeviceType and update the readme. After that I'll release a new version.

**Comment by Minaru** [comment]
I added the tvUserAgentDeviceType, updated the README and added some tests, some missing for old DeviceType, and some for the new ones (console/tv).

As you can see, the build is passing, and i hope my README update is alright according to your expectations for it. It's, in my opinion, ready to merge and release.

Feel free to give feedback on any missing things you would want before merging.

**Comment by rguerreiro** [comment]
It's great. Thanks

**Pull request merged**
