### PR TITLE
Hotfix/fix package json import webpack

### LINKED ISSUE #26: [Bug] Build issues with Angular project (webpack)
Webpack in an angular project seems to have issues with json imports when the extension of the file is not added in the require, as well as the package `useragent` having issues with `yamlparser` being in the wrong dependency property (is in dev deps, not in normal ones where it should).

screenshot from 2018-02-15 17-50-31

### PR DESCRIPTION
**Pull request by luchillo17**
Fixes https://github.com/rguerreiro/device/issues/26

The branch in my repo is already in a PR for `useragent` but seems like the project hasn't received an update in a while, so that's why i use my own branch meanwhile.

### CODE REVIEW

**Comment by ngfelixl** [comment]
Pay attention to this line in the dependencies in the **package.json** file.

```
"useragent": "luchillo17/useragent#hotfix/prod-deps-in-dev-deps"
```

I think this should not be merged this way. Create a PR in the official *useragent* library and use it as dependency.

In the **device.js** file the change to

```
require('../package.json').version
```

fixes the error

> Module not found: Error: Can't resolve '../package'

**Comment by luchillo17** [comment]
@ngfelixl I did make a PR for it, and got rejected, can you check the discussion to see if this PR is still valid?
https://github.com/3rd-Eden/useragent/pull/121

**Comment by rguerreiro** [comment]
Is this still an issue?

**Comment by luchillo17** [comment]
It probably is, I went to another library so I'm not looking at this anymore, good luck.

**Comment by luchillo17** [comment]
Actually no, it seems it's fixed by #33.

**Pull request closed without merging**
